### ISSUE TITLE
typeerror sap.ui.require.preload is not a function

### ISSUE THREAD

**Issue by impnguyen** [SAP/grunt-openui5#66]
Hi, 

with version 0.10.0 I build my component-preload and do not have any problems. After updating to 0.13.0 I will get this error message: 

"typeerror sap.ui.require.preload is not a function"

Does someone have the same problem?

screenshot: jquery.sap.global-dbg.js
![image](https://user-images.githubusercontent.com/2463861/37600270-23a5ee06-2b87-11e8-810e-38c6b061e4bb.png)

successfully requested component-preload.js
![image](https://user-images.githubusercontent.com/2463861/37600392-7c6b8f82-2b87-11e8-8928-afbd935830e2.png)

**Comment by matz3** [comment]
I guess you are using a UI5 version below 1.54, which isn't compatible with the new bundle format that has been added with #65 and released with `0.13.0`.
There is a [`compatVersion`](https://github.com/SAP/grunt-openui5#compatversion) option which should be set to the corresponding target UI5 version.

**Comment by kovboyjder** [comment]
Hi, I've tried with a library and added the combatVersion. But I am still getting the error. I am using the SAP Web-ide Full stack to build a library.

**Comment by mschleeweiss** [comment]
Wouldn't this be an example for an app that is built for v1.54?

**Comment by arunavamukherjee04** [comment]
@impnguyen can you please share the solution of this problem.
